GEMINI_API_KEY="AQ.Ab8RN6LDMxqX_XI0TRVojRElmbZkbK-z2EIZRKBRWdQywU9u1g"

DB_HOST="tramway.proxy.rlwy.net"
DB_USER="root"
DB_PASSWORD="nLCbuyxROuenUpXpFuGLNIyliOCqGoME"
DB_NAME="railway"
DB_PORT="23342"